name: Package Crawler

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  push:
    paths:
      - 'src'

jobs:
  build:
    name: Package
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/AlexandreBrisebois/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore DOTNET packages
      run: dotnet restore ./src/megaphone.crawler/megaphone.crawler.sln
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: crawler:latest, crawler:1.0.0-preview
        file: ./src/megaphone.crawler/megaphone.crawler/Dockerfile