name: Package Crawler

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  push:
    paths:
      - 'src/**'

jobs:
  build:
    name: Package
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        file: ./src/Dockerfile
        tags: |
            ${{ secrets.REGISTRY_URL }}/crawler:latest
            ${{ secrets.REGISTRY_URL }}/crawler:1.0.0-preview-$GITHUB_RUN_NUMBER