name: Package Crawler

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
    release:
      types:
        -created
jobs:
  build:
    name: Package
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x
        source-url: https://nuget.pkg.github.com/AlexandreBrisebois/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        build-args: |
            ${{ format('PAT={0}', secrets.GITHUB_TOKEN ) }}
        push: true
        file: ./src/Dockerfile
        tags: |
            ${{ format('{0}/crawler:latest',secrets.REGISTRY_URL) }}
            ${{ format('{0}/crawler:1.0.0-preview-{1}',secrets.REGISTRY_URL, github.run_number) }}